services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      platforms: ["linux/amd64"]  # Ensure correct architecture
    container_name: node_app
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: mydb
      JWT_SECRET: "rRSWlZeS7qqLn5vOk+2ZmETzUQOZyd2y8VdjPUznmR0="  # Placeholder, will be replaced by the generated secret
      JWT_SECRET_FILE: /app/secret.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules
    command: ["sh", "-c", "openssl rand -base64 32 > /app/secret.env && export JWT_SECRET=$(cat /app/secret.env) && npm start"]

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
 